spring.application.name=stock-market-data-aggregation-backend

spring.cassandra.contact-points=127.0.0.1
spring.cassandra.port=9042
spring.cassandra.keyspace-name=stock_keyspace
spring.cassandra.local-datacenter=datacenter1

spring.servlet.multipart.max-file-size=50MB
spring.servlet.multipart.max-request-size=50MB